# Generated by Django 5.0.2 on 2024-07-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
