# Generated by Django 5.0.2 on 2024-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amout',
            new_name='amount',
        ),
    ]
